### ISSUE TITLE
Namespace collision: inject

### ISSUE THREAD

**Issue by lwhorton** [mnichols/ankh#5]
I was trying to use `ankh.instance('lodash', require('lodash'))` but kept getting cryptic errors. After stepping through the resolve process, I was able to determine (part) of the problem

There seems to be a namespace collision, but I'm not sure at which point.
During `Kernel.prototype.resolveAll`, the `(keys, deps)` provided points to `lodash.reduce`. This could be due to the fact that `lodash.inject` is an alias for `lodash.reduce` and at some point ankh's `inject` is getting clobbered.

**Comment by mnichols** [comment]
Dont use lodash?
